version: '3.6'
services:
  node_template_svc:
    container_name: node_template_svc
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/usr/src/app/config/service-account.json
    volumes:
      - ./src:/usr/src/app/src
      - ./config:/usr/src/app/config
      - ./tests:/usr/src/app/tests
    env_file:
      - .env
    ports:
      - "9090:8080"
    networks:
      - node_template_svc_connect

networks:
  node_template_svc_connect:
