service:
  enabled: true
  type: NodePort
  annotations: {}
  ports:
    - name: http
      port: 80
      targetPort: 8080

ingress:
  annotations:
    cert-manager.io/cluster-issuer: "lets-encrypt-nginx"
  enabled: true
  hosts:
    - host: notification-service.gke-prod.payhippo.ng
      paths:
        - /
      servicePort: 80
  tls:
    - secretName: notification-service-gke-prod-payhippo-ng
      hosts:
        - notification-service.gke-prod.payhippo.ng
deployment:
  env: &env
    - name: APP_ENV
      value: "production"

envFromExternalSecret:
  - key: NOTIFICATION_SERVICE_SA_CRED_PROD
    name: service-account-creds


probes:
  enabled: true
  livenessProbe:
    failureThreshold: 20
    httpGet:
      path: /notification-service/health
      port: http
      scheme: HTTP
    initialDelaySeconds: 5
    periodSeconds: 20
    timeoutSeconds: 10
  readinessProbe: null
    # failureThreshold: 20
    # httpGet:
    #   path: /notification-service/health
    #   port: http
    #   scheme: HTTP
    # initialDelaySeconds: 5
    # periodSeconds: 60
    # timeoutSeconds: 3

resources:
  limits:
    cpu: '1'
    memory: 1.5Gi
  requests:
    cpu: '500m'
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 90
